### ISSUE TITLE
Logo parameter for SiteSelectorPDFGen tool is overwritten by ApplicationIcon from config.js

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#127]
The optional Logo input parameter for the SiteSelectorPDFGen tool is not honored.  Instead, the logo is controlled using the ApplicationIcon in the config.js.  

If a user indicates a custom logo when publishing the SiteSelectorPDFGen tool, that logo is overwritten by whatever is indicated by the ApplicationIcon in the config.js.

#111

**Comment by CTLocalGovTeam** [comment]
This is by design. Users need to configure the application icon only once in config.js and it will be honored in the pdf report. The app provides the app icon to gpservice everytime a report is requested. This eliminates the need to re-run the gp tool and publish again if users decide to change the app icon after the app is published.

**Comment by lindsayking** [comment]
Closing this issue.  We understand now that the parameter is required on the UI even if its input is overwritten by the content of the config.js.
