### ISSUE TITLE
Change Geoenrichment service authenication model to use the oauth 2.0 approach

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/site-selector#140]
In the current version of the site selector we are storing an AGOL username and password in the proxy.config file on the server the old best practice to embed anonymous access for a geoenrichment service.

We need to update the application to use the same approach used for the routing service to authenticate with the enrichment service https://developers.arcgis.com/authentication/accessing-arcgis-online-services/

@NikkiGolding @lindsayking This is marked at TBD because we decided to implement this after the re delivery of the Site Selector application.

**Comment by LindsayThomas** [comment]
Are we a go for this release?

**Comment by NikkiGolding** [comment]
@LindsayThomas We need to determine that. We need to test this proxy change to see if we are.

**Comment by lindsayking** [comment]
I will assess whether we can make this change now and whether app functionality is affected.

**Comment by lindsayking** [comment]
Changing the proxy.config to use a clientId and clientSecret rather than a username and password does not appear to work.  When I try to use a part of the application that uses the geoenrichment service, I get a 403 error:

![image](https://cloud.githubusercontent.com/assets/4316336/8662523/7ede674c-2975-11e5-9ae6-faa80d34b655.png)


When I plug the URL (http://50.18.115.76/SiteSelectorIssues/proxy/proxy.ashx?http://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver/GeoEnrichment/enrich) directly into chrome or check Fiddler, I get the error:
{error: {code: Forbidden,message:"Proxy is being used for an unsupported service: http://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver/GeoEnrichment/enrich"}}

**Comment by MikeTschudi** [comment]
The failing server's proxy configured "http://geoenrich.arcgis.com/arcgis/rest/" but with matchAll defaulting to false, so the URL "http://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver/GeoEnrichment/enrich" was not permitted through (or given access to the client id/secret).

**Comment by NikkiGolding** [comment]
@MikeTschudi  Then a simple change to the proxy parameter fixes it?

**Comment by MikeTschudi** [comment]
Yes. The 'development' branch version had the 'matchAll=true' and works once the app is registered. Remove the 'matchAll' line, and it immediately fails with the same message. The [proxy documentation](https://github.com/Esri/resource-proxy/tree/master/DotNet#proxy-configuration-settings) has a bit more about this.

**Comment by lindsayking** [comment]
@NikkiGolding @MikeTschudi   

The matchAll setting is also correctly set to "true" in the master branch.  No changes are needed to fix this issue at this time.
