### ISSUE TITLE
Android phone: User must tap Back to get back to app after downloading property/site reports

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#196]
On Android phones, when the user downloads either Property Information and Site Information reports, a new tab opens with a spinner while the report is processing.  The report then downloads and is available through the phone OS, but the spinner in the browser persists.  The user must tap "Back" in order to get back to the application.  Otherwise that new tab spins indefinitely.

Note: tapping "Back" returns to the correct application state.  Map and search changes persist.

**Comment by lindsayking** [comment]
For comparison, on iPhone, once the report finishes downloading, the browser tab stops spinning and displays the report.

**Comment by lindsayking** [comment]
We are seeing the behavior for the first time since support for phone devices has only recently been added.  https://github.com/Esri/site-selector/issues/176

**Comment by lindsayking** [comment]
@CTLocalGovTeam   Do you have any comment on this issue?

**Comment by CTLocalGovTeam** [comment]
@lindsayking 

We were able to reproduce this issue and have completed our analysis. This issue is with Chrome on Android smartphones only and we are now searching for a work-around.

**Comment by lindsayking** [comment]
@CTLocalGovTeam   Sounds good.  Please communicate any proposed workaround or approach before implementing.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 

We haven't been able to identify a suitable solution/workaround for this yet.

The current behavior of the app is because of the fix for issue #64, which was causing popup blockers on iOS devices while downloading the report. To avoid popup blockers, we first open a new browser window and set the location to report URL obtained from the GP service. Which displays reports on iOS devices without showing any popup. This fix is inherited from ‘Map Gallery(#71)’ and ‘Environmental Impact(#66)’.

We cannot close the new browser window automatically as the report is displayed in this window on iPhones.

**Comment by lindsayking** [comment]
@CTLocalGovTeam   Is it possible to detect when the download finishes and - when the download completes - display a message that says something like "The download has completed.  Check your downloads location for the report."?  (This error message should be included in the nls.)

In the scenario above, on iOS devices, this message would not appear because the pdf displays in the browser tab.  But on Android devices running Chrome, this message would display in the new browser tab that opens when the report is downloaded.

Is this a workaround we could use?  Keeping in mind we want to stay away from device-specific code.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
It is not possible to detect when the download finishes through JavaScript. 
We can display a message that the download has 'started' instead of 'completed' and inform user to 'check the downloads location if it does not display in the browser'.
On iOS devices, this message will be displayed for some time, till the download completes and the pdf opens in the browser window.

**Comment by lindsayking** [comment]
@CTLocalGovTeam 

As long as this text is configurable in the nls, please proceed with this approach.

**Comment by lindsayking** [comment]
We have decided not to implement this change at this time.  No further action required.
