### ISSUE TITLE
Evaluate whether the Web.config is required in the \proxy folder

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#217]
The Web.config is present in the proxy folder, but we need to confirm whether it is still needed, particularly now that we have updated to the 1.1 version of the proxy.

**Comment by kbusby** [comment]
I had many issues with the Proxy file and Tokens when I was setting mine up. We ended up using another Web.config from Git and it worked but getting to that point took a lot of trial and error.. mostly error. What made it worse was it would work sometimes then it would stop working for no reason. since updating the Web.config file we have had no issues with obtaining a token or using the GeoEnrichment service as we did prior.
