### ISSUE TITLE
ENH - Add the ability to turn off geoenrichment 

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/site-selector#229]
This may need some report updates

**Comment by LindsayThomas** [comment]
This should have a True\False setting in the configuration file as well. Should be located just above GeoEnrichment Services, in the same section

**Comment by MikeTschudi** [comment]
@LindsayThomas, @ChrisBuscaglia: branch `enable-geoenrich` has this enhancement; we can merge it into `development` if and when you want to.

It has been implemented in a redundant fashion:
1. If the geoenrichment service URL `GeoEnrichmentService` is null or an empty string, geoenrichment is disabled.
2. Otherwise, the new switch `EnableGeoEnrichmentService` (located as specified by Lindsay, above) controls enablement (`true` to enable; `false` to disable). For backwards compatibility, if this switch is omitted, it defaults to `true` and only `GeoEnrichmentService` controls enablement.

The switch isn't necessary because the URL can control the enablement, but it seems clearer to document.

**Comment by LindsayThomas** [comment]
@MikeTschudi Nice design choices. This helps folks maintained the current config but with the option to disable. I really like it.

**Comment by MikeTschudi** [comment]
Also, because the Business and Community tabs are only used with geoenrichment, they are only visible if geoenrichment is enabled.

**Comment by ChrisBuscaglia** [comment]
@MikeTschudi please add it to the development branch, thanks for the update!

**Comment by MikeTschudi** [comment]
@ChrisBuscaglia done!

**Comment by ChrisBuscaglia** [comment]
@MikeTschudi This fix looks good - any objections to close this issue for the Feb. release?  Did you have anything else that you wanted to incorporate/test?

**Comment by MikeTschudi** [comment]
@ChrisBuscaglia Looks good to me
