### ISSUE TITLE
Incorporate changes from Live Work Locate application

### ISSUE THREAD

**Issue by lindsayking** [Esri/site-selector#95]
Incorporate changes from Live Work Locate (https://github.com/Esri/live-work-locate/commit/e581eb33f38959d367de6652e1b8004ac2699b7f) into the Site Selector application.  Summarized below.

![image](https://cloud.githubusercontent.com/assets/4316336/5711926/19b0345a-9a63-11e4-977d-371403e310d8.png)

**Comment by lindsayking** [comment]
@MikeTschudi  @NikkiGolding 

Can either of you take a look at this to confirm the change was made?

**Comment by MikeTschudi** [comment]
I see obsolete-search-string handling and special-key handling in the code.  The special-key handling is an improvement over the live-work-locate version because it is using the AMD approach for the 'keys' constants; we should use this new work as our standard for other apps.

The differences in the sharing code between live-work-locate and site-selector are too great to tell if the site-selector version solves the same problem; I can only recommend the thorough testing that brand-new code would get.

**Comment by lindsayking** [comment]
Thanks @MikeTschudi

**Comment by LindsayThomas** [comment]
@lindsayking We need to ensure the following work for this scenario
Test Application using place names with Special Characters
Do critical search testing review (ensure we didn't lose functionality)
Do critical sharing testing review (ensure we didn't lose functionality)

**Comment by LindsayThomas** [comment]
Search for "D' " breaks in current and new version of apps 
Can't test sharing with special characters because they aren't searchable
